// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkFinder.Models;

namespace ParkFinderAPI.Migrations
{
    [DbContext(typeof(ParkFinderContext))]
    [Migration("20211205035531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkFinder.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsCityOrMunicipalPark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCountyPark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNationalPark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOtherFederalLand")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrivatePark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStatePark")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(135)
                        .HasColumnType("varchar(135) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Comments = "Breathtaking",
                            IsCityOrMunicipalPark = false,
                            IsCountyPark = false,
                            IsFree = false,
                            IsNationalPark = true,
                            IsOtherFederalLand = false,
                            IsPrivatePark = false,
                            IsStatePark = false,
                            Location = "Ashford, WA",
                            Name = "Mount Rainier National Park",
                            Rating = "5"
                        },
                        new
                        {
                            ParkId = 2,
                            Comments = "Wildflowers season is bonkers. The fee for a Central Cascades Wilderness Permit is minimal and totally worth it.",
                            IsCityOrMunicipalPark = false,
                            IsCountyPark = false,
                            IsFree = false,
                            IsNationalPark = false,
                            IsOtherFederalLand = true,
                            IsPrivatePark = false,
                            IsStatePark = false,
                            Location = "Sisters, Oregon",
                            Name = "Mount Jefferson Wilderness",
                            Rating = "5"
                        },
                        new
                        {
                            ParkId = 3,
                            Comments = "Whether you want a short hike or a long one, you can enjoy coastal forest, beaches and tidal pools here. An Oregon gem.",
                            IsCityOrMunicipalPark = false,
                            IsCountyPark = false,
                            IsFree = true,
                            IsNationalPark = false,
                            IsOtherFederalLand = false,
                            IsPrivatePark = false,
                            IsStatePark = true,
                            Location = "Arch Cape, OR",
                            Name = "Oswald West State Park",
                            Rating = "4"
                        },
                        new
                        {
                            ParkId = 4,
                            Comments = "While listed here as a County Park, Smith and Bybee is technically run by Metro, a regional form of government unique to the Portland Metropolitan Area. A lovely wetland great for paddling right in the city. Popular spot--be prepared for putting in and taking out (as well as parking) to be crowded. Once you're out on the water however, you can usually find some peace and quite to accompany your beautiful view.",
                            IsCityOrMunicipalPark = false,
                            IsCountyPark = true,
                            IsFree = true,
                            IsNationalPark = false,
                            IsOtherFederalLand = false,
                            IsPrivatePark = false,
                            IsStatePark = false,
                            Location = "Portland, OR",
                            Name = "Smith and Bybee Wetlands Natural Area",
                            Rating = "4"
                        },
                        new
                        {
                            ParkId = 5,
                            Comments = "Home to many great events including the downtown Vancouver Farmers Market.",
                            IsCityOrMunicipalPark = true,
                            IsCountyPark = false,
                            IsFree = true,
                            IsNationalPark = false,
                            IsOtherFederalLand = false,
                            IsPrivatePark = false,
                            IsStatePark = false,
                            Location = "Vancouver, WA",
                            Name = "Esther Short Park",
                            Rating = "3"
                        },
                        new
                        {
                            ParkId = 6,
                            Comments = "Truly a hidden gem of Portland. A beautiful garden with charming paths and a wonderful view of the Willamette River. Thank you to the Episcopal Diocese of Portland for this gift to the community.",
                            IsCityOrMunicipalPark = false,
                            IsCountyPark = false,
                            IsFree = true,
                            IsNationalPark = false,
                            IsOtherFederalLand = false,
                            IsPrivatePark = true,
                            IsStatePark = false,
                            Location = "Portland, OR",
                            Name = "Elk Rock Garden at Bishop's Close",
                            Rating = "4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
